---
name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration:
    name: Integration Tests with LSP
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        nvim-version:
          - v0.11.0
          - nightly
    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-version }}

      - name: Install plenary.nvim and Mason
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          git clone --depth 1 https://github.com/williamboman/mason.nvim ~/.local/share/nvim/site/pack/vendor/start/mason.nvim
          ln -s $(pwd) ~/.local/share/nvim/site/pack/vendor/start/dbt-lsp.nvim

      - name: Run tests
        run: make test

      - name: Install dbt-lsp manually for integration tests
        run: |
          curl -fsSL https://raw.githubusercontent.com/dbt-labs/dbt-fusion/main/crates/dbt-common/assets/install.sh | sh -s -- --package dbt-lsp
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run tests with dbt-lsp installed
        run: make test
